### ISSUE TITLE
github automatically disables scheduled workflows after 60 days of repo inactivity

### ISSUE THREAD

**Issue by cdepillabout** [cdepillabout/nix-haskell-updates-status#2]
Apparently GitHub disables workflows automatically after 60 days of inactivity in the repo.  It is possible to manually restart workflows after this happens.

It sounds like "activity" is limited to commits to the repo.

Here's various info about this around the web:

- https://github.community/t/do-disabled-scheduled-workflows-re-activate-on-repository-activity/160658/2
- https://github.community/t/no-notification-workflow-disabled-after-60-days/182169
- https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#disabling-and-enabling-workflows
- https://stackoverflow.com/questions/67184368/prevent-scheduled-github-actions-from-becoming-disabled

This may not affect us since our workflow commits to the repo, but we should still probably be on the lookout for problems.

**Comment by cdepillabout** [comment]
As of today, it appears that I haven't committed anything to this repo in over 60 days, so I imagine this is not actually a problem for us:

![image](https://user-images.githubusercontent.com/64804/135966988-1b7ef6e3-d940-447d-9cbe-d7a4a8669095.png)

**Comment by maralorn** [comment]
I think updates stopped two days ago?

**Comment by maralorn** [comment]
Oh, my bad. That was due to an eval error.

**Comment by cdepillabout** [comment]
This hasn't ended up being a problem for us, so I'll go ahead and close it.
